election/config/routes.rb
Rails.application.routes.draw do
  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :campaign_commitees

  resources :votes

  resources :districts

  resources :voivodships

  resources :users
  resource :user_session, only: [:create, :new, :destroy]

  root :to => "users#index"
  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

end

election/app/models/campaign_commitee.rb
class CampaignCommitee < ActiveRecord::Base
  has_many :votes
  has_and_belongs_to_many :voivodships

  validates :name, presence: true, length: {within: 2..50}
  validates :party, presence: true, length: {within: 2..50}
end

election/app/controllers/campaign_commitees_controller.rb
class CampaignCommiteesController < ApplicationController
  before_action :set_campaign_commitee, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate, :except => [:index,:show]

  # GET /campaign_commitees
  # GET /campaign_commitees.json
  def index
    @campaign_commitees = CampaignCommitee.all
  end

  # GET /campaign_commitees/1
  # GET /campaign_commitees/1.json
  def show
  end

  # GET /campaign_commitees/new
  def new
    @campaign_commitee = CampaignCommitee.new
  end

  # GET /campaign_commitees/1/edit
  def edit
  end

  # POST /campaign_commitees
  # POST /campaign_commitees.json
  def create
    @campaign_commitee = CampaignCommitee.new(campaign_commitee_params)

    respond_to do |format|
      if @campaign_commitee.save
        format.html { redirect_to @campaign_commitee, notice: 'Campaign commitee was successfully created.' }
        format.json { render :show, status: :created, location: @campaign_commitee }
      else
        format.html { render :new }
        format.json { render json: @campaign_commitee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campaign_commitees/1
  # PATCH/PUT /campaign_commitees/1.json
  def update
    respond_to do |format|
      if @campaign_commitee.update(campaign_commitee_params)
        format.html { redirect_to @campaign_commitee, notice: 'Campaign commitee was successfully updated.' }
        format.json { render :show, status: :ok, location: @campaign_commitee }
      else
        format.html { render :edit }
        format.json { render json: @campaign_commitee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaign_commitees/1
  # DELETE /campaign_commitees/1.json
  def destroy
    @campaign_commitee.destroy
    respond_to do |format|
      format.html { redirect_to campaign_commitees_url, notice: 'Campaign commitee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign_commitee
      @campaign_commitee = CampaignCommitee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def campaign_commitee_params
      params.require(:campaign_commitee).permit(:name, :logo, :party)
    end
end

election/app/helpers/campaign_commitees_helper.rb
module CampaignCommiteesHelper
end

election/app/views/campaign_commitees/_form.html.erb
<%= form_for(@campaign_commitee) do |f| %>
  <% if @campaign_commitee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@campaign_commitee.errors.count, "error") %> prohibited this campaign_commitee from being saved:</h2>

      <ul>
      <% @campaign_commitee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :logo %><br>
    <%= f.text_area :logo %>
  </div>
  <div class="field">
    <%= f.label :party %><br>
    <%= f.text_field :party %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

election/app/views/campaign_commitees/edit.html.erb
<h1>Editing Campaign Commitee</h1>

<%= render 'form' %>

<%= link_to 'Show', @campaign_commitee %> |
<%= link_to 'Back', campaign_commitees_path %>

election/app/views/campaign_commitees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Campaign Commitees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Logo</th>
      <th>Party</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @campaign_commitees.each do |campaign_commitee| %>
      <tr>
        <td><%= campaign_commitee.name %></td>
        <td><%= campaign_commitee.logo %></td>
        <td><%= campaign_commitee.party %></td>
        <td><%= link_to 'Show', campaign_commitee %></td>
        <td><%= link_to 'Edit', edit_campaign_commitee_path(campaign_commitee) %></td>
        <td><%= link_to 'Destroy', campaign_commitee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Campaign commitee', new_campaign_commitee_path %>

election/app/views/campaign_commitees/new.html.erb
<h1>New Campaign Commitee</h1>

<%= render 'form' %>

<%= link_to 'Back', campaign_commitees_path %>

election/app/views/campaign_commitees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @campaign_commitee.name %>
</p>

<p>
  <strong>Logo:</strong>
  <%= @campaign_commitee.logo %>
</p>

<p>
  <strong>Party:</strong>
  <%= @campaign_commitee.party %>
</p>

<%= link_to 'Edit', edit_campaign_commitee_path(@campaign_commitee) %> |
<%= link_to 'Back', campaign_commitees_path %>