election/config/routes.rb
Rails.application.routes.draw do
  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :campaign_commitees

  resources :votes

  resources :districts

  resources :voivodships

  resources :users
  resource :user_session, only: [:create, :new, :destroy]

  root :to => "users#index"
  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

end

election/app/models/voivodship.rb
class Voivodship < ActiveRecord::Base
  has_many :districts
  has_and_belongs_to_many :campaign_commitees

  validates :name, presence: true, length: {within: 7..50},
  confirmation: {
      message: "Wpisz poprawne województwo"
  }
end

election/app/controllers/voivodships_controller.rb
class VoivodshipsController < ApplicationController
  before_action :set_voivodship, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate, :except => [:index,:show]

  # GET /voivodships
  # GET /voivodships.json
  def index
    @voivodships = Voivodship.all
  end

  # GET /voivodships/1
  # GET /voivodships/1.json
  def show
  end

  # GET /voivodships/new
  def new
    @voivodship = Voivodship.new
  end

  # GET /voivodships/1/edit
  def edit
  end

  # POST /voivodships
  # POST /voivodships.json
  def create
    @voivodship = Voivodship.new(voivodship_params)

    respond_to do |format|
      if @voivodship.save
        format.html { redirect_to @voivodship, notice: 'Voivodship was successfully created.' }
        format.json { render :show, status: :created, location: @voivodship }
      else
        format.html { render :new }
        format.json { render json: @voivodship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /voivodships/1
  # PATCH/PUT /voivodships/1.json
  def update
    respond_to do |format|
      if @voivodship.update(voivodship_params)
        format.html { redirect_to @voivodship, notice: 'Voivodship was successfully updated.' }
        format.json { render :show, status: :ok, location: @voivodship }
      else
        format.html { render :edit }
        format.json { render json: @voivodship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /voivodships/1
  # DELETE /voivodships/1.json
  def destroy
    @voivodship.destroy
    respond_to do |format|
      format.html { redirect_to voivodships_url, notice: 'Voivodship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_voivodship
      @voivodship = Voivodship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def voivodship_params
      params.require(:voivodship).permit(:name)
    end
end

election/app/helpers/voivodships_helper.rb
module VoivodshipsHelper
end

election/app/views/voivodships/_form.html.erb
<%= form_for(@voivodship) do |f| %>
  <% if @voivodship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@voivodship.errors.count, "error") %> prohibited this voivodship from being saved:</h2>

      <ul>
      <% @voivodship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

election/app/views/voivodships/edit.html.erb
<h1>Editing Voivodship</h1>

<%= render 'form' %>

<%= link_to 'Show', @voivodship %> |
<%= link_to 'Back', voivodships_path %>

election/app/views/voivodships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Voivodships</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @voivodships.each do |voivodship| %>
      <tr>
        <td><%= voivodship.name %></td>
        <td><%= link_to 'Show', voivodship %></td>
        <td><%= link_to 'Edit', edit_voivodship_path(voivodship) %></td>
        <td><%= link_to 'Destroy', voivodship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Voivodship', new_voivodship_path %>

election/app/views/voivodships/new.html.erb
<h1>New Voivodship</h1>

<%= render 'form' %>

<%= link_to 'Back', voivodships_path %>

election/app/views/voivodships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @voivodship.name %>
</p>

<%= link_to 'Edit', edit_voivodship_path(@voivodship) %> |
<%= link_to 'Back', voivodships_path %>