election/config/routes.rb
Rails.application.routes.draw do
  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :campaign_commitees

  resources :votes

  resources :districts

  resources :voivodships

  resources :users
  resource :user_session, only: [:create, :new, :destroy]

  root :to => "users#index"
  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

end

election/app/models/commitee.rb
class Commitee < ActiveRecord::Base
  has_many :users
  validates :name, presence: true, length: {within: 2..50}
end

election/app/controllers/commitees_controller.rb
class CommiteesController < ApplicationController
  before_action :set_commitee, only: [:show, :edit, :update, :destroy]

  # GET /commitees
  # GET /commitees.json
  def index
    @commitees = Commitee.all
  end

  # GET /commitees/1
  # GET /commitees/1.json
  def show
  end

  # GET /commitees/new
  def new
    @commitee = Commitee.new
  end

  # GET /commitees/1/edit
  def edit
  end

  # POST /commitees
  # POST /commitees.json
  def create
    @commitee = Commitee.new(commitee_params)

    respond_to do |format|
      if @commitee.save
        format.html { redirect_to @commitee, notice: 'Commitee was successfully created.' }
        format.json { render :show, status: :created, location: @commitee }
      else
        format.html { render :new }
        format.json { render json: @commitee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /commitees/1
  # PATCH/PUT /commitees/1.json
  def update
    respond_to do |format|
      if @commitee.update(commitee_params)
        format.html { redirect_to @commitee, notice: 'Commitee was successfully updated.' }
        format.json { render :show, status: :ok, location: @commitee }
      else
        format.html { render :edit }
        format.json { render json: @commitee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commitees/1
  # DELETE /commitees/1.json
  def destroy
    @commitee.destroy
    respond_to do |format|
      format.html { redirect_to commitees_url, notice: 'Commitee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_commitee
      @commitee = Commitee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def commitee_params
      params.require(:commitee).permit(:name)
    end
end

election/app/helpers/commitees_helper.rb
module CommiteesHelper
end

election/app/views/commitees/_form.html.erb
<%= form_for(@commitee) do |f| %>
  <% if @commitee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@commitee.errors.count, "error") %> prohibited this commitee from being saved:</h2>

      <ul>
      <% @commitee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

election/app/views/commitees/edit.html.erb
<h1>Editing Commitee</h1>

<%= render 'form' %>

<%= link_to 'Show', @commitee %> |
<%= link_to 'Back', commitees_path %>

election/app/views/commitees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Commitees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @commitees.each do |commitee| %>
      <tr>
        <td><%= commitee.name %></td>
        <td><%= link_to 'Show', commitee %></td>
        <td><%= link_to 'Edit', edit_commitee_path(commitee) %></td>
        <td><%= link_to 'Destroy', commitee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Commitee', new_commitee_path %>

election/app/views/commitees/new.html.erb
<h1>New Commitee</h1>

<%= render 'form' %>

<%= link_to 'Back', commitees_path %>

election/app/views/commitees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @commitee.name %>
</p>

<%= link_to 'Edit', edit_commitee_path(@commitee) %> |
<%= link_to 'Back', commitees_path %>